"""add_field_text_and_remove_question_and_answer_in_timelines

Revision ID: 82b84d4aafa5
Revises: 3d41861b14a0
Create Date: 2023-09-20 14:14:08.722495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b84d4aafa5'
down_revision: Union[str, None] = '3d41861b14a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelines', sa.Column('text', sa.String(), nullable=True))
    op.drop_column('timelines', 'answer')
    op.drop_column('timelines', 'question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelines', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('timelines', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('timelines', 'text')
    # ### end Alembic commands ###
